[build-system]
requires = ["setuptools>=68.0"]
build-backend = "setuptools.build_meta"

[project]
name = "shuntly"
version = "0.8.0"
description = "A lightweight wiretap for LLM SDKs: capture all requests and responses with a single line of code"
requires-python = ">=3.10"
license = "MIT"
readme = "README.md"

[project.urls]
Homepage = "https://shuntly.ai"
Repository = "https://github.com/shuntly/shuntly-py"

[project.optional-dependencies]
dev = [
    "pytest==9.0.2",
    "anthropic==0.77.0",
    "openai==2.20.0",
    "google-genai==1.62.0",
    "ruff==0.15.0",
    "mypy==1.19.1",
    "nox==2025.11.12",
    "build==1.4.0",
    "litellm==1.81.10",
    "python-dotenv==1.2.1",
    "any-llm-sdk[openai]==1.8.5; python_version>='3.11'",
    "ollama==0.6.1",
    ]

[tool.setuptools.packages.find]
include = ["shuntly*"]


[tool.ruff]
line-length = 90
indent-width = 4

[tool.ruff.format]
quote-style = "single"
indent-style = "space"
skip-magic-trailing-comma = false
line-ending = "auto"
docstring-code-format = true
docstring-code-line-length = "dynamic"


[tool.mypy]
files = "shuntly/**/*.py"
show_error_codes = true
warn_redundant_casts = true
warn_unused_ignores = true
warn_unreachable = true
warn_return_any = true
warn_unused_configs = true
# disable_error_code = "misc"